### ISSUE TITLE
Improve text-overflow: ellipsis of actions

### ISSUE THREAD

**Issue by JordiParraCrespo** [Peersyst/near-mobile-wallet#235]
- Account: `adacolau.testnet`

![Image](https://user-images.githubusercontent.com/52425638/213991280-14ac85b0-04f6-41b9-8a42-e44a45ecfed6.png)

**Comment by silvap-javier** [comment]
file:///home/alerion/Descargas/WhatsApp%20Image%202023-01-25%20at%2006.57.55.jpeg
