### ISSUE TITLE
Sweat coin currency 

### ISSUE THREAD

**Issue by hackverd** [Peersyst/near-mobile-wallet#392]
After i sent sweat coin to the app I can't send it to another wallet there's no option to do that so it's just stuck there

**Comment by cartmangreko** [comment]
I have the exact same issue. I fear I have been scammed - there is no way to do anything with the sweatcoin after it arrived.

**Comment by AgustinMJ** [comment]
Hi guys! Sorry for the late response. Can you check that you have enough NEAR in your account to pay the fees? If so, could you share an explorer link to your address? In any case, you have not been scammed, don't worry! You can always access your funds with your mnemonic/private key, NEAR Mobile Wallet is just a tool to remove as much complexity as possible.
