### ISSUE TITLE
[Bug]: My near mobile wallet got compromissed

### ISSUE THREAD

**Issue by antonzolotar** [Peersyst/near-mobile-wallet#396]
### Can you describe the bug?

Hello,

I created a wallet using Near wallet mobile on 10th of October 2023 to stake my near coins. I used the Near Wallet Mobile to generate a seed phrase but I didn't save it anywhere. Then I transfered coins from Okex to that wallet and staked them.
After few months I opened this app and realised that I don't have funds there. Someone did unstake my funds and then sent them after 2 days to another address.

The problem is that I had never export or save this seed phrase anywhere (icloud, notes or somewhere else). That would have be a reason of how my wallet got hacked. But I used my Iphone 12 pro max which is secured and no one has access to it.
Then I installed Near Mobile app through the Apple store and generated a new wallet using this app.

So the question is how this seed phrase is generated? Is it generated locally on my phone or using 3rd party services? Which algorithm it uses to generate a seed phrase?

This is the address, where the funds were sent to d32d40b2f924463ad91d821a97ed5408b205859d8c74bf6eae0a6551d56c28a7.
Can you please help me to find out which exchange website this address belongs to.

![1](https://github.com/Peersyst/near-mobile-wallet/assets/41546491/fabb2884-1858-4c24-9c23-6f75cadf6e2a)
![2](https://github.com/Peersyst/near-mobile-wallet/assets/41546491/5d55e7a7-5132-479e-ba0c-15f226dfdf75)
![3](https://github.com/Peersyst/near-mobile-wallet/assets/41546491/548c2fe1-edff-4388-8f10-e8e45038e397)
![4](https://github.com/Peersyst/near-mobile-wallet/assets/41546491/7022a477-4381-47ae-a8b3-f0198710dbe1)
![5](https://github.com/Peersyst/near-mobile-wallet/assets/41546491/e064b0d5-a901-426b-8e29-7749e62afe9a)

### Operating system

IOS

**Comment by RomanQri** [comment]
Hi guys. Are you solved this issue ?

**Comment by whetherlove** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by AgustinMJ** [comment]
Hi @antonzolotar! Sorry for the late response. The mnemonic is generated locally on your phone using the [bip39-light](https://github.com/vacuumlabs/bip39-light) package, which is the same used by the oficial [near-seed-phrase](https://github.com/near/near-seed-phrase) NEAR package. [Here is the line of the code doing it](https://github.com/Peersyst/near-mobile-wallet/blob/868f0e1511ef86b3267b5f46de4bcbb80a1369ca/src/module/sdk/NearSdkService/NearSdkService.ts#L168).


I can also confirm that your mnemonic is stored in your device safely using Expo's [SecureStorage](https://docs.expo.dev/versions/latest/sdk/securestore/) package. This means, your mnemonic is stored in your iOS keychain (when using an iPhone) or encrypted in SharedPreferences (when using an Android). On both cases, your mnemonic is encrypted in your phone. [Here you can check the code for this](https://github.com/Peersyst/near-mobile-wallet/blob/868f0e1511ef86b3267b5f46de4bcbb80a1369ca/src/module/wallet/WalletStorage.ts#L64).

Having said that, it looks like no-one could have accessed your private key with NEAR Mobile Wallet🤔. We'll have a look at it anyway and let you know if we find something!
