### ISSUE TITLE
[Bug]: Wallet app is stuck on splash screen on Samsung flip 5

### ISSUE THREAD

**Issue by treizeku** [Peersyst/near-mobile-wallet#451]
### Can you describe the bug?

The near wallet app gets stuck on the startup splash screen on a Samsung flip 5 phone. I think it has to do with the more narrow screen or something (main screen, not cover screen). It works fine on my Samsung S22 ultra.

### Operating system

Android

**Comment by Hamidheyd** [comment]
HBIE

**Comment by treizeku** [comment]
This was solved by clearing the apps cache. So it didn't have anything to do with the screen.

**Comment by JordiParraCrespo** [comment]
Try to clean the cache and open it again if this does not work submit another issue. 
Thanks for opening the issue :smile:
