### ISSUE TITLE
Cant see my staked balance on near mobile wallet app

### ISSUE THREAD

**Issue by Goni1988** [Peersyst/near-mobile-wallet#483]
### Can you describe the bug?

A bug happened!
Cant see my staked balance on near mobile wallet app

### Operating system

IOS

**Comment by Roockeeeet** [comment]
#502

**Comment by Irfan957100** [comment]
> ### Can you describe the bug?
> A bug happened! Cant see my staked balance on near mobile wallet app
> 
> ### Operating system
> IOS

Same problem

**Comment by Irfan957100** [comment]
I staked my near coin but now I didn't saw it

**Comment by Irfan957100** [comment]
I staked my near coin but now I didn't saw it

**Comment by Irfan957100** [comment]
Same

**Comment by JordiParraCrespo** [comment]
Thank you for submitting this issue. 
Are you still facing the issue? You can contact us in telegram  [@NEARMobile](https://t.me/NEARMobile)
