### ISSUE TITLE
Update near-api-js dependency to the latest version

### ISSUE THREAD

**Issue by gtsonevv** [Peersyst/near-mobile-wallet#515]
`near-api-js` dependency will be upgraded to v4 in [wallet-selector](https://github.com/near/wallet-selector). The problem is that `[near-mobile-wallet](https://github.com/Peersyst/near-mobile-wallet)` uses an older version of the `near-api-js` package that is incompatible with the latest changes.
 
<img width="1079" alt="Screenshot 2024-07-03 at 10 53 53" src="https://github.com/Peersyst/near-mobile-wallet/assets/31661340/8835d536-f0dc-4c3c-b179-a6d45c9923d0">

Updating `near-api-js` to v4 will help us continue our work.

**Comment by pivanov** [comment]
Hey @AdriaCarrera :)
You can use the `update-naj-to-v4` branch from our repository as a starting point.
We've already updated all the necessary packages in this branch.

Here is the link to the branch: [LimeChain/wallet-selector/tree/update-naj-to-v4](https://github.com/LimeChain/wallet-selector/tree/update-naj-to-v4)

This should help in resolving the compatibility issues with the latest changes.

**Comment by JordiParraCrespo** [comment]
Hi! We apologize for the delay in responding. We are already working on the update and will upload a version with near-api-js v4 in the next few days.
Thank you for your patience and understanding.
