### ISSUE TITLE
can not manually import account on IOS 18.1

### ISSUE THREAD

**Issue by edxzh** [Peersyst/near-mobile-wallet#562]
### Operating system

IOS

### Version number

2.13

### Steps to reproduce

1. Open Near Mobile app
2. Go to settings by click the right top icon
3. Go to `Security` tab
4. Click `Import account manually` button

### Expected behavior

Show me the steps of importing account

### Actual behavior

the app exits

**Comment by JordiParraCrespo** [comment]
Hello! I next release this should be fixed
