### ISSUE TITLE
Can not manually import account on IOS 18.1

### ISSUE THREAD

**Issue by edxzh** [Peersyst/near-mobile-wallet#572]
### Operating system

IOS

### Version number

1.8.1

### Steps to reproduce

1. Open Near Mobile app
2. Go to settings by click the right top icon
3. Go to Security tab
4. Click Import account manually button
5. Input `{myneardomainalias}.near`
6. Click Import button

pops up `something went wrong`

### Expected behavior

the next steps of account import

I submitted an importing bug another day, is it possible to test the e2e import flow after the fix? thanks

### Actual behavior

"something went wrong"

**Comment by JordiParraCrespo** [comment]
Hello! Thank you for reporting this issue. We're happy to let you know that it has already been resolved in [PR #574](https://github.com/Peersyst/near-mobile-wallet/pull/574) and will be included in the upcoming release, version 1.8.2.

If you'd like to try it out beforehand, feel free to join our beta testing program via Telegram [here](https://t.me/vrcasadella). We'd love to hear your feedback!

**Comment by edxzh** [comment]
thanks @JordiParraCrespo , that's fine I can wait for the new release
